### ISSUE TITLE
Make protected properties & methods inside Zip Class

### ISSUE THREAD

**Issue by andreacivita** [zanysoft/laravel-zip#26]
Hi, i was trying to use this class and I need to extend it to add some features related to my business logic. 

I see that inside `ZanySoft\Zip\Zip` class, a lot of properties and methods are setted to `private`. 
This behaviour prevents me from extending class. 

Is it possible to change all `private` to `protected`? 

If necessary, I can submit a PR with these changes

**Comment by zanysoft** [comment]
Use version 2.0.x if you are using PHP 7.4 or 8.x
