### ISSUE TITLE
Image path not work properly after extract in specific folder.

### ISSUE THREAD

**Issue by faysal-web** [zanysoft/laravel-zip#28]
I want to upload monthly newsletter on my website with zip file, Upload and extract properly but when opening it HTML open properly but the image path not found properly example I upload January month newsletter but the image path show http://my website/images/newsletter/photo.jpg but my file is in http://my website/images/newsletter/january/photo.jpg how can I solve 

NB: HTML file and image file are in the same folder.

**Comment by zanysoft** [comment]
Image path not set properly in your newsletter html.
