### ISSUE TITLE
PHP Fatal error:  Unparenthesized `a ? b : c ? d : e` is not supported. in PHP 8.1, Laravel 9 Version

### ISSUE THREAD

**Issue by KRinnNet** [zanysoft/laravel-zip#32]
Hi,

I'm Receiving the Following Error after Updating the Laravel to Version 9 and PHP 8.1

----------------------------------------------------------------------------------------------------------------------------------------------
PHP Fatal error:  Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in C:\--------\vendor\zanysoft\laravel-zip\src\Zip.php on line 405

Symfony\Component\ErrorHandler\Error\FatalError

Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`
at C:\-----------\vendor\zanysoft\laravel-zip\src\Zip.php:405

    401         if (!is_array($files) && !is_string($files) && !is_null($files)) {
    402             throw new Exception('Invalid extractable files');
    403         }
    404
    405    $files = is_array($files) ? $files : is_string($files) ? [$files]: $files;
    406
    407         if (@sizeof($files) != 0 ) {
    408             $file_matrix = $files;
    409         } else {

  1   C:\-------\vendor\filp\whoops\src\Whoops\Run.php:486
      Whoops\Run::handleError()

  2   [internal]:0
      Whoops\Run::handleShutdown()
---------------------------------------------------------------------------------------------------------------------------------------------
Please help in rectifying

Thanks

**Comment by zanysoft** [comment]
Thanks for contacting us,

Yet laravel 9 not support we working on it and will push new version soon with compatibility of laravel 9 and PHP 8.x

________________________________
From: KR inn ***@***.***>
Sent: Friday, April 29, 2022 3:48 PM
To: zanysoft/laravel-zip ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [zanysoft/laravel-zip] PHP Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. in PHP 8.1, Laravel 9 Version (Issue #32)


Hi,

I'm Receiving the Following Error after Updating the Laravel to Version 9 and PHP 8.1

________________________________

PHP Fatal error: Unparenthesized a ? b : c ? d : e is not supported. Use either (a ? b : c) ? d : e or a ? b : (c ? d : e) in C:--------\vendor\zanysoft\laravel-zip\src\Zip.php on line 405

Symfony\Component\ErrorHandler\Error\FatalError

Unparenthesized a ? b : c ? d : e is not supported. Use either (a ? b : c) ? d : e or a ? b : (c ? d : e)
at C:-----------\vendor\zanysoft\laravel-zip\src\Zip.php:405

401         if (!is_array($files) && !is_string($files) && !is_null($files)) {
402             throw new Exception('Invalid extractable files');
403         }
404
405    $files = is_array($files) ? $files : is_string($files) ? [$files]: $files;
406
407         if ***@***.***($files) != 0 ) {
408             $file_matrix = $files;
409         } else {


1 C:-------\vendor\filp\whoops\src\Whoops\Run.php:486
Whoops\Run::handleError()

2 [internal]:0
Whoops\Run::handleShutdown()

Please help in rectifying

Thanks

**Comment by KRinnNet** [comment]
Hi Mubashar Ahmed,

Thank you fro responding very soon!

I have found out that this merge request from https://github.com/cbekir/laravel-zip/tree/patch-1 works perfectly! and have implemented temporarily.

Anyways waiting for the main release.

Thank You

**Comment by zanysoft** [comment]
Kindly use zanysoft/laravel-zip version 1.0.4 i have fixed this issue in new version

**Comment by moxi099** [comment]
Hello. I had the same problem with using aum in swow. The PHP version is 8.1.4
![image](https://user-images.githubusercontent.com/61492796/168205447-98e61d10-c0a4-43b4-bd57-a4f7fbbbef18.png)
