### ISSUE TITLE
Cannot assign Illuminate\Foundation\Application to property ZanySoft\Zip\Zip::$zip_file of type ?string

### ISSUE THREAD

**Issue by nabeeljavaid** [zanysoft/laravel-zip#34]
Hi, I have recently upgraded the package and now I am getting following error, I think $zip_file must be type of object not string

**Error:** Cannot assign Illuminate\Foundation\Application to property ZanySoft\Zip\Zip::$zip_file of type ?string
**Code:**
`
       $zipFiles = [
            '/var/www/cml/public/data/temp/new/01.pdf',
            '/var/www/cml/public/data/temp/new/02.pdf',
            '/var/www/cml/public/data/temp/new/02.pdf',
        ];
        $zip = Zip::create('/var/www/cml/public/data/temp/new.zip');
        $zip->add($zipFiles);
        $zip->close();
`
**Screenshot:** 
![Screenshot from 2022-06-22 13-12-14](https://user-images.githubusercontent.com/2786954/174979084-82d3fca9-9159-4a02-b6a4-1df204bc3069.png)

**Comment by Tarhex** [comment]
Any luck with this?

**Comment by Tarhex** [comment]
The error is from emanating from `vendor/zanysoft/laravel-zip/src/Zip.php` on Line 54 where we have:

` private ?string $zip_file = null;`

but will work if it is:

`private $zip_file = null;`

Waiting for them to fix it though as it is not a good practice to edit vendor files.

**Comment by szhorvath** [comment]
I have the same issue? any workarounds?

**Comment by giagara** [comment]
I have worked around by overriding the class:
```php
<?php

namespace App\Classes\Zip;

class Zip extends \ZanySoft\Zip\Zip{

    /**
     * Class constructor
     *
     * @param string $zip_file ZIP file name
     *
     */
    public function __construct($zip_file)
    {
        if (empty($zip_file)) {
            throw new \Exception(self::getStatus(ZipArchive::ER_NOENT));
        }

        if(is_string($zip_file) == true) {
            $this->zip_file = $zip_file;
        }

    }

}

```

And in my controller i use `use App\Classes\Zip\Zip;` or whatever namespace you have.

**Comment by ipimpat** [comment]
Same issue, using Laravel 9

**Comment by Tarhex** [comment]
use the workaround suggested by @giagara

**Comment by zanysoft** [comment]
Use V2 if you are using PHP 7.4+ or 8.x

**Comment by Tarhex** [comment]
@zanysoft It is V2 that has the issue

**Comment by hz61p1** [comment]
@zanysoft the problem is relevant

**Comment by mikaeldiok** [comment]
any solution?
