### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by BrekiTomasson** [zanysoft/laravel-zip#36]
In PHP 8.1, we can see that one of your methods (at least one) has a deprecation warning:

`PHP Deprecated:  ZipArchive::open(): Passing null to parameter #2 ($flags) of type int is deprecated in /var/www/vendor/zanysoft/laravel-zip/src/Zip.php on line 636`

This happens when I just `Zip::open($filename)`

The reason for this seems to be that your DocBlock defines `@param int $flags ZIP status code` but you are calling the method with `null` for this field. The DocBlock needs to be updated to allow `int` to be null, so `@param ?int $flags ZIP status code`

**Comment by zanysoft** [comment]
fixed
