### ISSUE TITLE
Issue with zip from MacOS device

### ISSUE THREAD

**Issue by KyoRion** [zanysoft/laravel-zip#37]
When I archive folder from MAC it'll auto generate __MACOXS folder into zip file and when I using method check it throw for me Exception error please check it
![image](https://user-images.githubusercontent.com/26852023/177944495-5dd6c260-90cd-4ecf-ab23-a99f491b9c2b.png)

**Comment by marvyco** [comment]
same, any help?

**Comment by minkbear** [comment]
same here

**Comment by zanysoft** [comment]
remove __MACOXS before archive.
