### ISSUE TITLE
Laravel 9+ Issue On Unparenthesized

### ISSUE THREAD

**Issue by dev-techguy** [zanysoft/laravel-zip#41]
Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` at /var/www/ksa/vendor/zanysoft/laravel-zip/src/Zip.php:405)

**Comment by goszowski** [comment]
Use version ^2.0

**Comment by dev-techguy** [comment]
It worked thanks
